gp_registrations_mi_repo_param_name="/registrations/dev/gp-registrations-mi/ecr/url/mi-api"
log_group_param_name="/registrations/dev/gp-registrations-mi/cloudwatch-log-group-name"
execution_role_arn_param_name="/registrations/dev/gp-registrations-mi/ecs-execution-role-arn"
vpc_id_param_name="/registrations/dev/gp-registrations-mi/base-networking/vpc-id"
vpc_cidr_block_param_name="/registrations/dev/gp-registrations-mi/base-networking/vpc-cidr-block"
ecs_cluster_arn_param_name="/registrations/dev/gp-registrations-mi/ecs-cluster/ecs-cluster-arn"
private_subnet_ids_param_name="/registrations/dev/gp-registrations-mi/base-networking/private-subnet-ids"
apigee_ips_param_name="/registrations/dev/user-input/gp-registrations-mi/apigee-ips"